[tool.poetry]
name = "sport-arbitrage"
version = "0.1.0"
description = ""
authors = ["herculesgimenes"]
readme = "README.md"
packages = [{include = "sport-arbitrage"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
